npcs:
  npc:
    name: test
    texture: eyJ0aW1lc3RhbXAiOjE1ODY1MDU2Njg5OTAsInByb2ZpbGVJZCI6Ijg2NjdiYTcxYjg1YTQwMDRhZjU0NDU3YTk3MzRlZWQ3IiwicHJvZmlsZU5hbWUiOiJTdGV2ZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGMxYzc3Y2U4ZTU0OTI1YWI1ODEyNTQ0NmVjNTNiMGNkZDNkMGNhM2RiMjczZWI5MDhkNTQ4Mjc4N2VmNDAxNiJ9LCJDQVBFIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTUzY2FjOGI3NzlmZTQxMzgzZTY3NWVlMmI4NjA3MWE3MTY1OGYyMTgwZjU2ZmJjZThhYTMxNWVhNzBlMmVkNiJ9fX0
    signature: R33sizvZLNGhaEWGvxJnxg0U7B39r0BDCC3vdPXTVZuvTStHllFxkm6L+ZJlfCwg/0VhJ734W2qmJ0+3Xd65/HJU0qBaa5qV9ayJiQe9/aK2kZaL4lYLjuRU7HuG2TrGQPOF+8QCS8oelCKFaKWoxhfi2J3ut8svNrTEhAFWbIPWjBAeL5YqIe8+vHRo9mlntrnwWbjKsSue4grjsHKgYC4G50f8qhRduEkThERtbXZMR/OmlSAPuzy6b78sZ5uU3SGwCNRxfT2biCfVmWA5hrPMl9PHYz/LEZKHB2GSqeV8f9janD4MHoV8ImmEu9AIMY6bxEdqBZI8PxIsI43YBzw6M+Zui/m+JSavUSZ8nRUJ2hAKe6UtVoPJpyNe/+tafzWYSHNW2mcjsMrnI2KWD4g0Ff/9nXGLEF7FaZlGpoyZwEd3a7oH1IgOOANl04G3lNEkXdZHR/o8H1/ZZC36GMJGf5udF3kScrLhcNyMBmMc2FrVkTonqZ/Wwb9XTWqB9tQIK6Rcj8rngl4cQmYp4DfFARnpAxA3JYqKhWwtBWQO35nDm3ILZ63My6DRzoMmfsrPoTtigVzeOPk8X1gaLRvv11uXplVfedRx3/dF9kScYARPlX+urjy4UWWrtpRllgd1eqdHZWVFbQXWFWdMiq+tF80lh7AxP3IZSE//TwU=
    uuid: 62ce816c-7a9d-11ea-bc55-0242ac130003
    interact: ServersGUI
    location:
      world: world
      x: 40
      y: 80
      z: 85
      yaw: 0.0
      pitch: 0.0